import turtle
turtle.showturtle()
turtle.write("Welcome to turtle world")
turtle.forward(100)
turtle.right(90)
turtle.forward(20)
turtle.color("red")
turtle.forward(100)
turtle.right(90)
turtle.color("green")
turtle.goto(0,0)
turtle.penup()
turtle.goto(100,100)
turtle.pendown()
turtle.goto(0,0)
turtle.circle(100)
turtle.done()